### ISSUE TITLE
Add Landing Page for LogIn and Registration

### ISSUE THREAD

**Issue by Jayesh-Sinnarkar** [divyanshu-tiwari/Shram-Sevak#39]
Add landing page for login and registration where customer and worker can choose to login to website or create new accont.

**Comment by TarjanSahu** [comment]
it is almost complete I'll upload  as soon as possible.

**Comment by TarjanSahu** [comment]
I have Uploaded my given task 
Check out and we need to have some configuration  CSS file in body

**Comment by TarjanSahu** [comment]
And I also do routing configuration for Login And signUp

**Comment by TarjanSahu** [comment]
work is done

**Comment by TarjanSahu** [comment]
closing
