### ISSUE TITLE
image handling

### ISSUE THREAD

**Issue by divyanshu-tiwari** [divyanshu-tiwari/Shram-Sevak#63]
know issues 
- null values of profilePicturePath in the http request not accepted in the database.
- find a way to implement default profilePicture for both worker and customer
- image handling not implemented in both worker and customer

**Comment by TarjanSahu** [comment]
Working On it

**Comment by TarjanSahu** [comment]
Add new Dependency for image handling
<groupId>commons-io</groupId>

**Comment by TarjanSahu** [comment]
Add Image Handling For Customers And Workers
Also Set Path For Customer For Images/Customer
And path For Worker Images/Workers
Custum Name - Formate --> userId_1

**Comment by TarjanSahu** [comment]
Work Id Done
