### ISSUE TITLE
Implement following Back-End APIs for State, City and Locality

### ISSUE THREAD

**Issue by Jayesh-Sinnarkar** [divyanshu-tiwari/Shram-Sevak#99]
State: Fetch Data from states and display drop down to worker while sign up -> getAllStates()
City: List all cities from database which are from state selected by worker display drop down to worker while sign up -> getAllCitiesByStateId();
Locality:  List all localities from database which are from city selected by worker display drop down to worker while sign up -> getAllLocalitiesByCityId();

**Comment by TarjanSahu** [comment]
Work in Progress

**Comment by TarjanSahu** [comment]
work id done
